export const categoriasClima = [
    {
        code: 1000,
        day: 'Sunny',
        night: 'Clear',
        icon: 113,
        iconLocal: 'Sun.png',
    },
    {
        code: 1003,
        day: 'Partly cloudy',
        night: 'Partly cloudy',
        icon: 116,
        iconLocal: 'DayClouds.png',
    },
    {
        code: 1006,
        day: 'Cloudy',
        night: 'Cloudy',
        icon: 119,
        iconLocal: 'Clouds.png',
    },
    {
        code: 1009,
        day: 'Overcast',
        night: 'Overcast',
        icon: 122,
        iconLocal: 'DayClouds.png',
    },
    {
        code: 1030,
        day: 'Mist',
        night: 'Mist',
        icon: 143,
        iconLocal: 'DayClouds.png',
    },
    {
        code: 1063,
        day: 'Patchy rain possible',
        night: 'Patchy rain possible',
        icon: 176,
        iconLocal: 'DayRain.png',
    },
    {
        code: 1066,
        day: 'Patchy snow possible',
        night: 'Patchy snow possible',
        icon: 179,
        iconLocal: 'DaySnow.png',
    },
    {
        code: 1069,
        day: 'Patchy sleet possible',
        night: 'Patchy sleet possible',
        icon: 182,
        iconLocal: 'DayStorm.png',
    },
    {
        code: 1072,
        day: 'Patchy freezing drizzle possible',
        night: 'Patchy freezing drizzle possible',
        icon: 185,
        iconLocal: 'DayStorm.png',
    },
    {
        code: 1087,
        day: 'Thundery outbreaks possible',
        night: 'Thundery outbreaks possible',
        icon: 200,
        iconLocal: 'DayStorm.png',
    },
    {
        code: 1114,
        day: 'Blowing snow',
        night: 'Blowing snow',
        icon: 227,
        iconLocal: 'DayWind.png',
    },
    {
        code: 1117,
        day: 'Blizzard',
        night: 'Blizzard',
        icon: 230,
        iconLocal: 'DayWind.png',
    },
    {
        code: 1135,
        day: 'Fog',
        night: 'Fog',
        icon: 248,
        iconLocal: 'Night Fog.png',
    },
    {
        code: 1147,
        day: 'Freezing fog',
        night: 'Freezing fog',
        icon: 260,
        iconLocal: 'Night Fog.png',
    },
    {
        code: 1150,
        day: 'Patchy light drizzle',
        night: 'Patchy light drizzle',
        icon: 263,
        iconLocal: 'NightRain.png',
    },
    {
        code: 1153,
        day: 'Light drizzle',
        night: 'Light drizzle',
        icon: 266,
        iconLocal: 'NightRain.png',
    },
    {
        code: 1168,
        day: 'Freezing drizzle',
        night: 'Freezing drizzle',
        icon: 281,
        iconLocal: 'NightRain.png',
    },
    {
        code: 1171,
        day: 'Heavy freezing drizzle',
        night: 'Heavy freezing drizzle',
        icon: 284,
        iconLocal: 'NightRain.png',
    },
    {
        code: 1180,
        day: 'Patchy light rain',
        night: 'Patchy light rain',
        icon: 293,
        iconLocal: 'NightRain.png',
    },
    {
        code: 1183,
        day: 'Light rain',
        night: 'Light rain',
        icon: 296,
        iconLocal: 'NightRain.png',
    },
    {
        code: 1186,
        day: 'Moderate rain at times',
        night: 'Moderate rain at times',
        icon: 299,
        iconLocal: 'NightRain.png',
    },
    {
        code: 1189,
        day: 'Moderate rain',
        night: 'Moderate rain',
        icon: 302,
        iconLocal: 'NightRain.png',
    },
    {
        code: 1192,
        day: 'Heavy rain at times',
        night: 'Heavy rain at times',
        icon: 305,
        iconLocal: 'NightRain.png',
    },
    {
        code: 1195,
        day: 'Heavy rain',
        night: 'Heavy rain',
        icon: 308,
        iconLocal: 'NightRain.png',
    },
    {
        code: 1198,
        day: 'Light freezing rain',
        night: 'Light freezing rain',
        icon: 311,
        iconLocal: 'Night Storm.png',
    },
    {
        code: 1201,
        day: 'Moderate or heavy freezing rain',
        night: 'Moderate or heavy freezing rain',
        icon: 314,
        iconLocal: 'Night Storm.png',
    },
    {
        code: 1204,
        day: 'Light sleet',
        night: 'Light sleet',
        icon: 317,
        iconLocal: 'Night Storm.png',
    },
    {
        code: 1207,
        day: 'Moderate or heavy sleet',
        night: 'Moderate or heavy sleet',
        icon: 320,
        iconLocal: 'Night Storm.png',
    },
    {
        code: 1210,
        day: 'Patchy light snow',
        night: 'Patchy light snow',
        icon: 323,
        iconLocal: 'Night Snow.png',
    },
    {
        code: 1213,
        day: 'Light snow',
        night: 'Light snow',
        icon: 326,
        iconLocal: 'Night Snow.png',
    },
    {
        code: 1216,
        day: 'Patchy moderate snow',
        night: 'Patchy moderate snow',
        icon: 329,
        iconLocal: 'Night Snow.png',
    },
    {
        code: 1219,
        day: 'Moderate snow',
        night: 'Moderate snow',
        icon: 332,
        iconLocal: 'Night Snow.png',
    },
    {
        code: 1222,
        day: 'Patchy heavy snow',
        night: 'Patchy heavy snow',
        icon: 335,
        iconLocal: 'Night Snow.png',
    },
    {
        code: 1225,
        day: 'Heavy snow',
        night: 'Heavy snow',
        icon: 338,
        iconLocal: 'Night Snow.png',
    },
    {
        code: 1237,
        day: 'Ice pellets',
        night: 'Ice pellets',
        icon: 350,
        iconLocal: 'Night Storm.png',
    },
    {
        code: 1240,
        day: 'Light rain shower',
        night: 'Light rain shower',
        icon: 353,
        iconLocal: 'NightRain.png',
    },
    {
        code: 1243,
        day: 'Moderate or heavy rain shower',
        night: 'Moderate or heavy rain shower',
        icon: 356,
        iconLocal: 'NightRain.png',
    },
    {
        code: 1246,
        day: 'Torrential rain shower',
        night: 'Torrential rain shower',
        icon: 359,
        iconLocal: 'NightRain.png',
    },
    {
        code: 1249,
        day: 'Light sleet showers',
        night: 'Light sleet showers',
        icon: 362,
        iconLocal: 'Night Storm.png',
    },
    {
        code: 1252,
        day: 'Moderate or heavy sleet showers',
        night: 'Moderate or heavy sleet showers',
        icon: 365,
        iconLocal: 'Night Storm.png',
    },
    {
        code: 1255,
        day: 'Light snow showers',
        night: 'Light snow showers',
        icon: 368,
        iconLocal: 'Night Snow.png',
    },
    {
        code: 1258,
        day: 'Moderate or heavy snow showers',
        night: 'Moderate or heavy snow showers',
        icon: 371,
        iconLocal: 'Night Snow.png',
    },
    {
        code: 1261,
        day: 'Light showers of ice pellets',
        night: 'Light showers of ice pellets',
        icon: 374,
        iconLocal: 'Night Storm.png',
    },
    {
        code: 1264,
        day: 'Moderate or heavy showers of ice pellets',
        night: 'Moderate or heavy showers of ice pellets',
        icon: 377,
        iconLocal: 'Night Storm.png',
    },
    {
        code: 1273,
        day: 'Patchy light rain with thunder',
        night: 'Patchy light rain with thunder',
        icon: 386,
        iconLocal: 'NightRain.png',
    },
    {
        code: 1276,
        day: 'Moderate or heavy rain with thunder',
        night: 'Moderate or heavy rain with thunder',
        icon: 389,
        iconLocal: 'NightRain.png',
    },
    {
        code: 1279,
        day: 'Patchy light snow with thunder',
        night: 'Patchy light snow with thunder',
        icon: 392,
        iconLocal: 'Night Snow.png',
    },
    {
        code: 1282,
        day: 'Moderate or heavy snow with thunder',
        night: 'Moderate or heavy snow with thunder',
        icon: 395,
        iconLocal: 'Night Snow.png',
    },
];
